# Site settings
title: fjh1997
SEOTitle: Blog of fjh1997
header-img: img/NorwayPool.jpg
email: fjhhz1997@gmail.com
description: "God don't move that mountain,instead let me to climb."
keyword: "hackintosh, fjh1997, linux, openwrt, NAT"
url: "http://fjh1997.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/fjh1997/fjh1997.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I‘m a clumsy bird,And I have to start flying earlier."
sidebar-avatar: /img/myPhoto.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     fjh1997
github_username:    fjh1997
facebook_username:  100023121155214
jianshu_username:   a5878132d89d
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e0b4c6c675803d5ea3f4                           #生成的clientID
  clientSecret: 85d7f6e9aea67e246ee6998b8ef21c07ae7dc645    #生成的clientSecret
  accessToken: 58201fe0dda7a97b69e95a5531ce384649a5018b 
  repo: fjh1997.github.io    #仓库名称
  owner: fjh1997    #github用户名
  admin: fjh1997
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 52c2603844447535fd71d855cc73cc9f

# Google Analytics
ga_track_id: 'UA-135902752-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "KYZ",
        href: "http://kangyuzhe666.github.io"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "CoolShell",
        href: "https://coolshell.cn"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
